-- Sync the terminal emulator colors with the active colorscheme.
-- Every time a colorscheme loads, its palette (g:terminal_color_*, falling
-- back to highlight groups for themes that don't set them) is written to a
-- theme file for each terminal, and every running terminal is reloaded:
--   alacritty  ~/.config/alacritty/nvim-theme.toml  imported, live config reload
--   kitty      ~/.config/kitty/nvim-theme.conf      included, reloaded with SIGUSR1
--   ghostty    ~/.config/ghostty/themes/nvim-sync   theme, reloaded with AppleScript
-- Must be required before config.transparency, which clears Normal's bg.
local M = {}

local home = vim.env.HOME
local paths = {
    alacritty = home .. "/.config/alacritty/nvim-theme.toml",
    kitty = home .. "/.config/kitty/nvim-theme.conf",
    ghostty = home .. "/.config/ghostty/themes/nvim-sync",
}

local function hex(v)
    if type(v) == "number" then
        return string.format("#%06x", v)
    end
    if type(v) == "string" then
        if v:match("^#%x%x%x%x%x%x$") then
            return v:lower()
        end
        local n = vim.api.nvim_get_color_by_name(v)
        return n ~= -1 and hex(n) or nil
    end
end

local function hl(name, attr)
    local h = vim.api.nvim_get_hl(0, { name = name, link = false })
    if h.reverse then
        attr = attr == "fg" and "bg" or "fg"
    end
    return hex(h[attr])
end

-- a blended t of the way from color a to color b
local function mix(a, b, t)
    local x, y = tonumber(a:sub(2), 16), tonumber(b:sub(2), 16)
    local out = 0
    for shift = 16, 0, -8 do
        local ca = math.floor(x / 2 ^ shift) % 256
        local cb = math.floor(y / 2 ^ shift) % 256
        out = out + math.floor(ca + (cb - ca) * t + 0.5) * 2 ^ shift
    end
    return hex(out)
end

-- ANSI slot -> highlight groups to borrow its fg from, for themes that don't
-- set g:terminal_color_*
local fallback = {
    [1] = { "DiagnosticError", "ErrorMsg" },
    [2] = { "String", "DiagnosticOk" },
    [3] = { "DiagnosticWarn", "WarningMsg" },
    [4] = { "Function", "Directory" },
    [5] = { "Keyword", "Statement" },
    [6] = { "Special", "DiagnosticHint" },
}

function M.palette()
    local dark = vim.o.background == "dark"
    local bg = hl("Normal", "bg") or (dark and "#000000" or "#ffffff")
    local fg = hl("Normal", "fg") or (dark and "#ffffff" or "#000000")
    local derived = {
        [0] = dark and mix(bg, fg, 0.2) or fg,
        [7] = dark and mix(fg, bg, 0.15) or mix(bg, fg, 0.25),
        [8] = hl("Comment", "fg") or mix(bg, fg, 0.45),
        [15] = dark and fg or mix(bg, fg, 0.1),
    }
    for i, groups in pairs(fallback) do
        for _, g in ipairs(groups) do
            derived[i] = derived[i] or hl(g, "fg")
        end
        derived[i] = derived[i] or fg
    end

    local colors = {}
    for i = 0, 15 do
        colors[i] = hex(vim.g["terminal_color_" .. i])
            or derived[i]
            or derived[i - 8]
    end
    return {
        name = vim.g.colors_name or "unknown",
        bg = bg,
        fg = fg,
        cursor = hl("Cursor", "bg") or fg,
        sel_bg = hl("Visual", "bg") or mix(bg, fg, 0.25),
        sel_fg = hl("Visual", "fg") or fg,
        colors = colors,
    }
end

local render = {}

function render.alacritty(p)
    local c = p.colors
    local names = { "black", "red", "green", "yellow", "blue", "magenta", "cyan", "white" }
    local function block(title, offset)
        local out = { "[colors." .. title .. "]" }
        for i, n in ipairs(names) do
            out[#out + 1] = string.format('%s = "%s"', n, c[i - 1 + offset])
        end
        return table.concat(out, "\n")
    end
    local function pair(title, a, ak, b, bk)
        return string.format('[colors.%s]\n%s = "%s"\n%s = "%s"', title, ak, a, bk, b)
    end
    return table.concat({
        "# Generated by nvim (lua/config/termsync.lua) from " .. p.name .. ", do not edit",
        pair("primary", p.bg, "background", p.fg, "foreground"),
        pair("selection", p.sel_fg, "text", p.sel_bg, "background"),
        pair("vi_mode_cursor", p.bg, "text", c[4], "cursor"),
        pair("search.matches", p.bg, "foreground", c[8], "background"),
        pair("search.focused_match", p.bg, "foreground", c[2], "background"),
        pair("footer_bar", p.bg, "foreground", c[8], "background"),
        pair("hints.start", p.bg, "foreground", c[3], "background"),
        pair("hints.end", p.bg, "foreground", c[8], "background"),
        block("normal", 0),
        block("bright", 8),
        block("dim", 0),
    }, "\n\n") .. "\n"
end

function render.kitty(p)
    local c = p.colors
    local out = {
        "# Generated by nvim (lua/config/termsync.lua) from " .. p.name .. ", do not edit",
        "foreground " .. p.fg,
        "background " .. p.bg,
        "selection_foreground " .. p.sel_fg,
        "selection_background " .. p.sel_bg,
        "cursor " .. p.cursor,
        "cursor_text_color " .. p.bg,
        "url_color " .. c[4],
        "active_border_color " .. c[4],
        "inactive_border_color " .. c[8],
        "bell_border_color " .. c[3],
        "active_tab_foreground " .. p.bg,
        "active_tab_background " .. c[4],
        "inactive_tab_foreground " .. p.fg,
        "inactive_tab_background " .. p.bg,
        "tab_bar_background " .. p.bg,
    }
    for i = 0, 15 do
        out[#out + 1] = string.format("color%d %s", i, c[i])
    end
    return table.concat(out, "\n") .. "\n"
end

function render.ghostty(p)
    local out = {
        "# Generated by nvim (lua/config/termsync.lua) from " .. p.name .. ", do not edit",
        "background = " .. p.bg,
        "foreground = " .. p.fg,
        "cursor-color = " .. p.cursor,
        "cursor-text = " .. p.bg,
        "selection-background = " .. p.sel_bg,
        "selection-foreground = " .. p.sel_fg,
    }
    for i = 0, 15 do
        out[#out + 1] = string.format("palette = %d=%s", i, p.colors[i])
    end
    return table.concat(out, "\n") .. "\n"
end

-- writes the file only when its content changed, returns whether it did
local function write(path, content)
    local f = io.open(path, "r")
    if f then
        local old = f:read("*a")
        f:close()
        if old == content then
            return false
        end
    end
    vim.fn.mkdir(vim.fn.fnamemodify(path, ":h"), "p")
    f = io.open(path, "w")
    if not f then
        return false
    end
    f:write(content)
    f:close()
    return true
end

-- alacritty reloads by itself (it watches imported files), kitty and ghostty
-- are told to, but only when running so the AppleScript never launches ghostty
local function reload(changed)
    if not (changed.kitty or changed.ghostty) then
        return
    end
    vim.system({ "ps", "-axco", "pid=,comm=" }, { text = true }, function(r)
        local ghostty = false
        for line in (r.stdout or ""):gmatch("[^\n]+") do
            local pid, comm = line:match("^%s*(%d+)%s+(.-)%s*$")
            if comm == "kitty" and changed.kitty then
                vim.uv.kill(tonumber(pid), "sigusr1")
            elseif comm == "ghostty" then
                ghostty = true
            end
        end
        if ghostty and changed.ghostty then
            vim.system({
                "osascript",
                "-e",
                'tell application "Ghostty" to perform action "reload_config" on terminal 1',
            })
        end
    end)
end

function M.sync()
    local p = M.palette()
    local changed = {}
    for term, path in pairs(paths) do
        changed[term] = write(path, render[term](p))
    end
    reload(changed)
end

local group = vim.api.nvim_create_augroup("termsync", { clear = true })

-- drop the previous theme's terminal colors, so a theme that doesn't set them
-- falls back to its highlight groups instead of inheriting stale ones
vim.api.nvim_create_autocmd("ColorSchemePre", {
    group = group,
    callback = function()
        for i = 0, 15 do
            vim.g["terminal_color_" .. i] = nil
        end
    end,
})

vim.api.nvim_create_autocmd("ColorScheme", {
    group = group,
    callback = M.sync,
})

return M
